language: r
sudo: required
warnings_are_errors: true

os:
  - linux
  - osx

before_install:
  - echo "options(repos = c(CRAN='https://cran.rstudio.com/'))" > ~/.Rprofile

apt_packages:
  - libgsl0-dev

brew_packages:
  - gsl

r_github_packages:
  - jimhester/covr

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'library(covr); coveralls()'; fi

notifications:
  email:
    on_success: change
    on_failure: change
