# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgsl0-dev

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: oldrel
    - r: release
      r_packages: covr
      env: R_CODECOV=true
    - r: devel
    - os: osx
      brew_packages: gsl

after_failure:
  - cat "${RCHECK_DIR}/00install.out"

# Only report coverage for the release version on linux
after_success:
  - test ${R_CODECOV} && Rscript -e "covr::coveralls()"
  - cat "${RCHECK_DIR}/00install.out"

notifications:
  email:
    on_success: change
    on_failure: change
