# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - devscripts
      - libgsl0-dev

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: 3.4
    - r: oldrel
    - r: release
      r_packages: covr
      r_github_packages: jimhester/lintr
      env: R_CODECOV=true R_LINTR=true

after_failure:
  - cat "${RCHECK_DIR}/00install.out"

# Only report coverage for the release version on linux
after_success:
  - test ${R_CODECOV} && Rscript -e "covr::coveralls()"
  - test ${R_LINTR} && R CMD INSTALL $PKG_TARBALL
  - test ${R_LINTR} && Rscript -e "lintr::lint_package(linters = lintr::with_defaults(object_name_linter = NULL, object_usage_linter = NULL))"
  - cat "${RCHECK_DIR}/00install.out"

notifications:
  email:
    on_success: change
    on_failure: change
