# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libgsl0-dev

matrix:
  include:
    - r: 3.1
    - r: 3.2
    - r: 3.3
    - r: oldrel
    - r: release
      env: R_CODECOV=true
    - r: devel

# Only report coverage for the release version on linux
after_success:
  - test $R_CODECOV && Rscript -e "covr::coveralls()"

notifications:
  email:
    on_success: change
    on_failure: change
