steps:
- script: |
    curl -fLo /tmp/R.pkg "https://cloud.r-project.org/bin/macosx/R-3.6.3.pkg"
    sudo installer -pkg "/tmp/R.pkg" -target /
    rm /tmp/R.pkg
    curl -fLo /tmp/BasicTeX.pkg https://ctan.org/tex-archive/systems/mac/mactex/BasicTeX.pkg
    sudo installer -pkg "/tmp/BasicTeX.pkg" -target /
    rm /tmp/BasicTeX.pkg
    echo "##vso[task.prependpath]/usr/texbin"
    echo "##vso[task.prependpath]/Library/TeX/texbin"
    sudo tlmgr update --self
    sudo tlmgr install inconsolata courier courier-scaled helvetic
    brew install ghostscript
  displayName: "Install R"
