steps:
- bash: |
    sudo apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install \
      gdebi-core \
      qpdf \
      texinfo \
      texlive-extra-utils \
      texlive-fonts-recommended \
      texlive-fonts-extra \
      texlive-latex-recommended
    curl -fLo /tmp/R.deb https://cdn.rstudio.com/r/ubuntu-1804/pkgs/r-3.3.3_1_amd64.deb
    sudo gdebi --non-interactive /tmp/R.deb
    rm /tmp/R.deb
    echo '##vso[task.prependpath]/opt/R/3.3.3/bin'
  displayName: "Install R"
